"""add currency to source_countries

Revision ID: 2e77decb51a7
Revises: a4a28728cc82
Create Date: 2026-03-08 13:32:02.333888
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e77decb51a7'
down_revision = 'a4a28728cc82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_countries', sa.Column('currency', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_countries', 'currency')
    # ### end Alembic commands ###
