"""
train_categorizer.py
────────────────────
Trains the LightGBM job categorizer from labeled CSV data and saves
the model artifact used by the /v1/process endpoint.

Usage:
    python scripts/train_categorizer.py \\
        --data data/categorizer_training.csv \\
        --categories data/categories.csv \\
        --output models/categorizer.pkl

Input files (generated by scripts/generate_training_data.py):
    data/categories.csv
        Columns: id, title

    data/categorizer_training.csv
        Columns: title, original_category, description_plaintext, category_id

Output artifact:
    models/categorizer.pkl
        pickle.dump({
            "pipeline": sklearn.pipeline.Pipeline,   # TF-IDF + LGBMClassifier
            "id_to_category": {int: {"id": int, "title": str}},
        })
"""

import argparse
import os
import pickle
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
import lightgbm as lgb


def _progress_callback(period: int = 50):
    def callback(env):
        if (env.iteration + 1) % period == 0 or env.iteration + 1 == env.end_iteration:
            print(f"  [{env.iteration + 1}/{env.end_iteration}] iterations", flush=True)
    callback.order = 10
    return callback


def build_text(row: pd.Series) -> str:
    title = str(row.get("title") or "")
    original_category = str(row.get("original_category") or "")
    description = str(row.get("description_plaintext") or "")[:1000]
    return f"{title} {original_category} {description}"


def main() -> None:
    parser = argparse.ArgumentParser(description="Train LightGBM job categorizer")
    parser.add_argument("--data", required=True, help="Path to categorizer_training.csv")
    parser.add_argument("--categories", required=True, help="Path to categories.csv")
    parser.add_argument("--output", required=True, help="Path to write .pkl artifact")
    parser.add_argument("--n-estimators", type=int, default=300)
    parser.add_argument("--num-leaves", type=int, default=63)
    args = parser.parse_args()

    print(f"Loading training data from {args.data} ...")
    df = pd.read_csv(args.data).fillna("")
    print(f"  {len(df)} rows loaded")

    print(f"Loading categories from {args.categories} ...")
    cats = pd.read_csv(args.categories)
    id_to_category = {
        int(row["id"]): {"id": int(row["id"]), "title": str(row["title"])}
        for _, row in cats.iterrows()
    }
    print(f"  {len(id_to_category)} categories loaded")

    X = df.apply(build_text, axis=1).tolist()
    y = df["category_id"].astype(int).tolist()

    print("Vectorizing text (TF-IDF) ...", flush=True)
    tfidf = TfidfVectorizer(max_features=20_000, ngram_range=(1, 2), sublinear_tf=True)
    X_vec = tfidf.fit_transform(X)
    print(f"  Done — matrix shape: {X_vec.shape}", flush=True)

    print("Training LightGBM classifier ...", flush=True)
    clf = lgb.LGBMClassifier(
        n_estimators=args.n_estimators,
        num_leaves=args.num_leaves,
        n_jobs=-1,
        force_col_wise=True,
        verbose=-1,
        callbacks=[_progress_callback(1)],
    )
    clf.fit(X_vec, y)
    print("  Training complete", flush=True)

    pipeline = Pipeline([("tfidf", tfidf), ("clf", clf)])

    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
    with open(args.output, "wb") as f:
        pickle.dump({"pipeline": pipeline, "id_to_category": id_to_category}, f)
    print(f"Saved artifact to {args.output}")


if __name__ == "__main__":
    main()
