"""
train_categorizer.py
────────────────────
Trains the LightGBM job categorizer from labeled CSV data and saves
the model artifact used by the /v1/process endpoint.

Usage:
    python scripts/train_categorizer.py \\
        --data data/categorizer_training.csv \\
        --output models/categorizer.pkl

Input file (generated by scripts/generate_training_data.py):
    data/categorizer_training.csv
        Columns: title, original_category, description_plaintext, category_id

Output artifact:
    models/categorizer.pkl
        pickle.dump({
            "tfidf": TfidfVectorizer,             # fitted
            "booster": lgb.Booster,               # trained native booster
            "id_to_category": {int: {"id": int, "title": str}},
            "num_classes": int,
        })
"""

import argparse
import os
import pickle
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
import lightgbm as lgb

from scripts.generate_training_data import CATEGORIES


def build_text(row: pd.Series) -> str:
    title = str(row.get("title") or "")
    original_category = str(row.get("original_category") or "")
    description = str(row.get("description_plaintext") or "")[:1000]
    return f"{title} {original_category} {description}"


def main() -> None:
    parser = argparse.ArgumentParser(description="Train LightGBM job categorizer")
    parser.add_argument("--data", required=True, help="Path to categorizer_training.csv")
    parser.add_argument("--output", required=True, help="Path to write .pkl artifact")
    parser.add_argument("--n-estimators", type=int, default=500)
    parser.add_argument("--num-leaves", type=int, default=63)
    parser.add_argument("--early-stopping", type=int, default=30, help="Early stopping rounds")
    args = parser.parse_args()

    print(f"Loading training data from {args.data} ...")
    df = pd.read_csv(args.data).fillna("")
    print(f"  {len(df)} rows loaded")

    id_to_category = {cat_id: {"id": cat_id, "title": title} for cat_id, title in CATEGORIES}
    num_classes = len(id_to_category)

    X_text = df.apply(build_text, axis=1).tolist()
    # LightGBM multiclass expects 0-based labels
    y = (df["category_id"].astype(int) - 1).tolist()

    print("Vectorizing text (TF-IDF) ...", flush=True)
    tfidf = TfidfVectorizer(max_features=20_000, ngram_range=(1, 2), min_df=5, sublinear_tf=True)
    X_vec = tfidf.fit_transform(X_text)
    print(f"  Done — matrix shape: {X_vec.shape}", flush=True)

    # Train/validation split for early stopping + progress logging
    X_train, X_val, y_train, y_val = train_test_split(
        X_vec, y, test_size=0.1, random_state=42, stratify=y
    )

    print("Building LightGBM datasets ...", flush=True)
    train_data = lgb.Dataset(X_train, label=y_train, free_raw_data=True)
    val_data = lgb.Dataset(X_val, label=y_val, reference=train_data, free_raw_data=True)
    print("  Done", flush=True)

    params = {
        "objective": "multiclass",
        "num_class": num_classes,
        "metric": "multi_logloss",
        "num_leaves": args.num_leaves,
        "n_jobs": -1,
        "force_col_wise": True,
        "verbosity": -1,
    }

    print("Training ...", flush=True)
    booster = lgb.train(
        params,
        train_data,
        num_boost_round=args.n_estimators,
        valid_sets=[val_data],
        valid_names=["val"],
        callbacks=[
            lgb.early_stopping(stopping_rounds=args.early_stopping, verbose=True),
            lgb.log_evaluation(period=10),
        ],
    )
    print(f"  Best iteration: {booster.best_iteration}", flush=True)

    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
    with open(args.output, "wb") as f:
        pickle.dump({
            "tfidf": tfidf,
            "booster": booster,
            "id_to_category": id_to_category,
            "num_classes": num_classes,
        }, f)
    print(f"Saved artifact to {args.output}")


if __name__ == "__main__":
    main()
