"""
train_categorizer.py
────────────────────
Trains the LightGBM job categorizer from labeled CSV data and saves
the model artifact used by the /v1/process endpoint.

Usage:
    python scripts/train_categorizer.py \\
        --data data/categorizer_training.csv \\
        --output models/categorizer.pkl

Input file (generated by scripts/generate_training_data_labelled.py):
    data/categorizer_training.csv
        Columns: title, description_plaintext, category_id

    original_category is not used as a feature — the model learns purely from
    title + description content, matching inference-time conditions exactly.

Output artifact:
    models/categorizer.pkl
        pickle.dump({
            "tfidf": TfidfVectorizer,             # fitted
            "booster": lgb.Booster,               # trained native booster
            "id_to_category": {int: {"id": int, "title": str}},
            "num_classes": int,
        })
"""

import argparse
import os
import pickle
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
import lightgbm as lgb

from scripts.generate_training_data import CATEGORIES


def build_text(row: pd.Series) -> str:
    title = str(row.get("title") or "")
    description = str(row.get("description_plaintext") or "")
    return f"{title} {title} {title} {description}"


def main() -> None:
    parser = argparse.ArgumentParser(description="Train LightGBM job categorizer")
    parser.add_argument("--data", default="data/categorizer_training.csv", help="Path to categorizer_training.csv (default: data/categorizer_training.csv)")
    parser.add_argument("--output", default="models/categorizer.pkl", help="Path to write .pkl artifact (default: models/categorizer.pkl)")
    parser.add_argument("--n-estimators", type=int, default=500)
    parser.add_argument("--num-leaves", type=int, default=31)
    parser.add_argument("--early-stopping", type=int, default=50, help="Early stopping rounds")
    args = parser.parse_args()

    print(f"Loading training data from {args.data} ...")
    df = pd.read_csv(args.data).fillna("")
    print(f"  {len(df)} rows loaded")
    if df.empty:
        sys.exit(
            "Error: training data is empty.\n"
            "Generate it first:\n"
            "  python scripts/generate_training_data.py --output data/"
        )

    id_to_category = {cat_id: {"id": cat_id, "title": title} for cat_id, title in CATEGORIES}
    num_classes = len(id_to_category)

    df_train = df
    X_text = df_train.apply(build_text, axis=1).tolist()
    # LightGBM multiclass expects 0-based labels
    y = (df_train["category_id"].astype(int) - 1).tolist()

    print("Vectorizing text (TF-IDF) ...", flush=True)
    n_rows = len(df)
    max_features = min(20_000, max(2_000, n_rows // 2))
    min_df = 1 if n_rows < 10_000 else 5
    tfidf = TfidfVectorizer(max_features=max_features, ngram_range=(1, 2), min_df=min_df, sublinear_tf=True)
    X_vec = tfidf.fit_transform(X_text)
    print(f"  Done — matrix shape: {X_vec.shape}", flush=True)

    # Train/validation split for early stopping + progress logging
    X_train, X_val, y_train, y_val = train_test_split(
        X_vec, y, test_size=0.1, random_state=42, stratify=y
    )

    print("Building LightGBM datasets ...", flush=True)
    train_data = lgb.Dataset(X_train, label=y_train, free_raw_data=True)
    val_data = lgb.Dataset(X_val, label=y_val, reference=train_data, free_raw_data=True)
    print("  Done", flush=True)

    params = {
        "objective": "multiclass",
        "num_class": num_classes,
        "metric": "multi_logloss",
        "num_leaves": args.num_leaves,
        "learning_rate": 0.03,
        "min_data_in_leaf": 10,
        "lambda_l1": 0.5,
        "lambda_l2": 0.5,
        "feature_fraction": 0.8,
        "bagging_fraction": 0.8,
        "bagging_freq": 5,
        "n_jobs": -1,
        "force_col_wise": True,
        "verbosity": -1,
    }

    print("Training ...", flush=True)
    booster = lgb.train(
        params,
        train_data,
        num_boost_round=args.n_estimators,
        valid_sets=[val_data],
        valid_names=["val"],
        callbacks=[
            lgb.early_stopping(stopping_rounds=args.early_stopping, verbose=True),
            lgb.log_evaluation(period=10),
        ],
    )
    print(f"  Best iteration: {booster.best_iteration}", flush=True)

    print("\nEvaluating on validation set ...", flush=True)
    y_val_probs = booster.predict(X_val)
    y_val_pred = np.argmax(y_val_probs, axis=1)
    category_names = [title for _, title in CATEGORIES]
    print(classification_report(y_val, y_val_pred, target_names=category_names, digits=3))

    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
    with open(args.output, "wb") as f:
        pickle.dump({
            "tfidf": tfidf,
            "booster": booster,
            "id_to_category": id_to_category,
            "num_classes": num_classes,
        }, f)
    print(f"Saved artifact to {args.output}")


if __name__ == "__main__":
    main()
