"""create source_countries and jobs tables

Revision ID: a4a28728cc82
Revises: 
Create Date: 2026-03-08 12:35:16.400097
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4a28728cc82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('source_db', sa.VARCHAR(length=128), nullable=False),
    sa.Column('source_job_id', sa.BIGINT(), nullable=False),
    sa.Column('site_id', sa.SMALLINT(), nullable=False),
    sa.Column('external_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('company_id', sa.BIGINT(), nullable=True),
    sa.Column('company_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('site_title', sa.VARCHAR(length=100), nullable=True),
    sa.Column('url', sa.TEXT(), nullable=False),
    sa.Column('city_id', sa.BIGINT(), nullable=True),
    sa.Column('city_title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('region_id', sa.BIGINT(), nullable=True),
    sa.Column('region_title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('country_code', sa.CHAR(length=2), nullable=True),
    sa.Column('salary_min', sa.NUMERIC(precision=15, scale=2), nullable=True),
    sa.Column('salary_max', sa.NUMERIC(precision=15, scale=2), nullable=True),
    sa.Column('salary_period', sa.VARCHAR(length=10), nullable=True),
    sa.Column('salary_currency', sa.CHAR(length=3), nullable=True),
    sa.Column('contract', sa.VARCHAR(length=64), nullable=True),
    sa.Column('experience', sa.VARCHAR(length=255), nullable=True),
    sa.Column('education', sa.VARCHAR(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_remote', sa.BOOLEAN(), server_default='false', nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default='true', nullable=False),
    sa.Column('title_normalized', sa.TEXT(), nullable=True),
    sa.Column('description_clean', sa.TEXT(), nullable=True),
    sa.Column('description_html', sa.TEXT(), nullable=True),
    sa.Column('embedding', sa.TEXT(), nullable=True),
    sa.Column('embedded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_db', 'site_id', 'external_id', name='uq_jobs_source_external'),
    sa.UniqueConstraint('source_db', 'source_job_id', name='uq_jobs_source_pk')
    )
    op.create_index('idx_jobs_active_pub', 'jobs', ['is_active', 'published_at'], unique=False)
    op.create_index('idx_jobs_country_active_pub', 'jobs', ['country_code', 'is_active', 'published_at'], unique=False)
    op.create_index('idx_jobs_remote_active_pub', 'jobs', ['is_remote', 'is_active', 'published_at'], unique=False)
    op.create_table('source_countries',
    sa.Column('db_name', sa.String(length=128), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('db_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_countries')
    op.drop_index('idx_jobs_remote_active_pub', table_name='jobs')
    op.drop_index('idx_jobs_country_active_pub', table_name='jobs')
    op.drop_index('idx_jobs_active_pub', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
