INSERT INTO categories (id, title) VALUES
(1,  'Manufacturing & Engineering'),
(2,  'Automotive'),
(3,  'Food & Beverage Manufacturing'),
(4,  'IT & Telecommunications'),
(6,  'Construction & Infrastructure'),
(7,  'Consulting & Advisory'),
(8,  'Human Resources'),
(9,  'Transportation & Logistics'),
(10, 'Healthcare & Medical Services'),
(11, 'Aerospace & Defense'),
(12, 'Financial Services & Banking'),
(13, 'Real Estate & Architecture'),
(14, 'Marketing, Advertising & Media'),
(15, 'Hospitality & Restaurants'),
(16, 'Retail, Wholesale & Customer Service'),
(17, 'Education & Science'),
(18, 'Energy & Natural Resources'),
(20, 'Nonprofit & Government'),
(21, 'Arts, Entertainment & Recreation'),
(22, 'Legal Services'),
(25, 'Security & Surveillance'),
(26, 'Other')
ON CONFLICT (id) DO NOTHING;
