INSERT INTO categories (id, title) VALUES
(1,  'Manufacturing & Engineering'),
(2,  'Automotive'),
(3,  'Food & Beverage Manufacturing'),
(4,  'IT & Telecommunications'),
(5,  'Construction & Infrastructure'),
(6,  'Consulting & Advisory'),
(7,  'Human Resources'),
(8,  'Transportation & Logistics'),
(9,  'Healthcare & Medical Services'),
(10, 'Aerospace & Defense'),
(11, 'Financial Services & Banking'),
(12, 'Real Estate & Architecture'),
(13, 'Marketing, Advertising & Media'),
(14, 'Hospitality & Restaurants'),
(15, 'Retail, Wholesale & Customer Service'),
(16, 'Education & Science'),
(17, 'Energy & Natural Resources'),
(18, 'Nonprofit & Government'),
(19, 'Arts, Entertainment & Recreation'),
(20, 'Legal Services'),
(21, 'Security & Surveillance'),
(22, 'Other')
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title;
